[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
base64 = "0.13.0"
serde_json = "1.0.73"
serde = { version = "1.0", features = ["derive"] }